### PR TITLE
TDD testing and implementation for datetime.date().replace() and datetime.date.fromisoformat()

### PR DESCRIPTION
**Pull request by R055A**
# Requirements

    Python v3.85
    Java v8
    Junit v5
    JaCoCo v0.8.6

# Instructions

    - Open the voc/ directory as a project in IntelliJ
    - In File -> Project Structure -> Project -> Project SDK select Java 1.8
    - It may be required to disable android. If so, also in Project Settings, select Modules -> Sources, right click python/android and select Excluded
    - Navigate to voc/python/test/python/stdlib/datetime/
    - Junit5 may require being installed. If so, right click on any junit import, select Show Context Actions and select junit5
    - In Edit Configurations... -> Add New Configuration (the + symbol), select Junit
    - JaCoCo can be selected in Edit Configurations.. -> Code Coverage -> Choose Coverage Runner
    - Either right-click in the test file or on the directory to run all 75 tests or click the green run button on the left of each test to run them individually. 
    - The tests for datetime.date().replace() and datetime.date.fromisoformat() are listed below

# Tested functionality (following any and all fixes and refactoring)

#### Instance attributes
   
    + year: final Int
    + month: final Int
    + day: final Int

#### Instance methods

    + Date(Object[], Map<String, Object>): Date()
    + replace(Object year, Object month, Object day): Date()
    + __repr__(): String

#### Class methods

    + fromisoformat(Object): Date() <<static>>

#### Private methods (not tested directly)

    - validateThreeInputs(): void
    - validateArgTypes(): void
    - validateKwargTypes(): void
    - validateAttributeRanges(): void

# Test cases

    + testDateReplaceThreeValidInputs(): void
    + testDateReplaceOneValidArgInput(): void
    + testDateReplaceTwoValidArgInputs(): void
    + testDateFromIsoFormatValidDateString(): void
    + testDateFromIsoFormatInvalidDateStringArguments(): void
    + testDateFromIsoFormatInvalidArgumentTypes(): void
    + testDateFromIsoFormatValidStringInvalidDateRanges(): void
    + testDateFromIsoFormatWithDate__repr__(): void

# Notes

Testing is focused on all of the different possible outputs when using the Python datetime.date().replace() instance method for all Python types and value ranges for each different variation between args and kwargs input for each different number of inputs in total. 

For the class method, datetime.date.fromisoformat(), testing focus is on all of the different possible outputs for all Python types and value formats and ranges.

### CODE REVIEW

**Review by ponterik — CHANGES_REQUESTED** [review]
Good job overall I have a few requested changes to increase read and maintainability.


_____________________________
**Date.java**

There are alot of repitions of DateTimeEnum.XXXX.toString()  consider moving it to one variable declaration at the beginning of the method to increase readability and make it so that you only have to change the code in one place if you want to change that value later. e.g. String dayStr = DateTimeEnum.DAY.toString();


Change the "i" variable to something more descriptive to increase readability on line 429. Maybe attributeChanged?

**Comment by R055A** [comment]
> 
> 
> Good job overall I have a few requested changes to increase read and maintainability.
> 
> **Date.java**
> 
> There are alot of repitions of DateTimeEnum.XXXX.toString() consider moving it to one variable declaration at the beginning of the method to increase readability and make it so that you only have to change the code in one place if you want to change that value later. e.g. String dayStr = DateTimeEnum.DAY.toString();
> 
> Change the "i" variable to something more descriptive to increase readability on line 429. Maybe attributeChanged?

Thank you for the review!

I'm not an expert on the matter, but I think the enum request is debatable. Enums are constants, so I can't see the purpose for setting them to local variables for the method when most of the enums used are only used once. I don't think it will improve readability because the variable names will be just the same as the enum names. Being that they are enums they can already be changed in just one place, which is in the enum class. Please, correct me if I am wrong. 

As for the request to change the variable 'i' in line 429 to something more descriptive to increase readability, I have done this and changed it to 'numArgsSetToAttributes'. I will commit and push this now.

**Comment by ponterik** [comment]
Thats a fair point I will approve the pull request

**Review by ponterik — APPROVED** [review]

**Comment by R055A** [comment]
> 
> 
> Thats a fair point I will approve the pull request

Thank you, @ponterik! Actually, a new bug has been found and must be fixed first. If you run the Python TranspileTestCase tests you will see.

**Review by DavidOstlund — APPROVED** [review]

**Pull request merged**
